### ISSUE TITLE
Tracking: improving the release team shadow application process and sharing information with the community

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes-sigs/release-team-shadow-stats#4]
Reporting on the release team's shadow applicants in a way that is transparent to the community is a broader effort that requires collusion across multiple signatures. 

This topic should track that effort.

cc @justaugustus @jeremyrickard

**Comment by leonardpahlke** [comment]
Some more issues have been created...

- [x] [Updated the release-team's shadow application survey to add an opt-in option](https://github.com/kubernetes-sigs/release-team-shadow-stats/issues/10)
- [ ] [Document process: create, review and share the release-team-shadow-stats report](https://github.com/kubernetes-sigs/release-team-shadow-stats/issues/9)
- [ ] [Update documentation: use release-team-shadow-stats at the start of the release-cycle 1.25](https://github.com/kubernetes/sig-release/issues/1883)
- [ ]  [Which diagrams can be made publicly available in a report - consult contribex](https://github.com/kubernetes-sigs/release-team-shadow-stats/issues/7)
- [ ] [Add new charts for 1.25 release team shadow applicant survey](https://github.com/kubernetes-sigs/release-team-shadow-stats/issues/11)
- [x] [Highlight that the examples are being generated with fake / dummy data](https://github.com/kubernetes-sigs/release-team-shadow-stats/issues/12)

Long term:
- [ ]  [Define release-team-shadow report](https://github.com/kubernetes-sigs/release-team-shadow-stats/issues/8)
- [ ]  [Improve project usability](https://github.com/kubernetes-sigs/release-team-shadow-stats/issues/6)
- [ ]  [Change chart type of applicant timezones from a pie chart to a map](https://github.com/kubernetes-sigs/release-team-shadow-stats/issues/16)

**Comment by leonardpahlke** [comment]
cc 1.25 release lead @cici37 & @reylejano
